### ISSUE TITLE
cannot build tool with DC=dmd

### ISSUE THREAD

**Issue by linkrope** [funkwerk/cogito#2]
Maybe you should use `which` in `make.rb` so that both `DC=dmd` and `DC=/home/user/dlang/dmd-2.098.1/linux/bin64/dmd` will work.
Otherwise, `BIN_PATH` will be set to the directory where this repository has been checked out.

**Comment by belka-ew** [comment]
I replaced this with a Makefile. You can build a release with `make install build/release/bin/cogito`. There is `make release` aswell but it builds a zip file additionally and puts the binary into a different directory under `build`.
I changed the default `DC` value to an absolute path and `make DC=dmd …` seems to work. Does it work for you now?
